FROM jhaiduce/healthdata

USER root

WORKDIR /test

COPY requirements.test.txt /test
RUN pip3 install -r /test/requirements.test.txt

COPY integration_tests.py /test

ENV NAME World

RUN adduser --system --shell /bin/sh --no-create-home --group testuser

USER testuser

CMD ["pytest","/test/integration_tests.py","-s"]
