version: '3.7'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: jhaiduce/healthdata
    container_name: healthdata_web
    secrets:
      - source: pyramid_main_ini
        target: /run/secrets/production.ini
    logging:
      driver: journald
    links:
      - db
