version: '3.7'
secrets:
  storage_key.1:
    file: ./integration_test_secrets/storage_key.keyfile
  mysql_root_password.1:
    file: ./integration_test_secrets/db_root_pw
  mysql_production_password.3:
    file: ./integration_test_secrets/db_app_pw
  pyramid_auth_secret.1:
    file: ./integration_test_secrets/pyramid_auth_secret
  pyramid_main_ini:
    file: ./integration_test_secrets/integration_test.ini
  mysql_ca:
    file: ./integration_test_secrets/ca.pem
  mysql_cert:
    file: ./integration_test_secrets/server-cert.pem
  mysql_key:
    file: ./integration_test_secrets/server-key.pem
configs:
  mysql-config.1:
    file: ./mysql-config-healthdata.cnf
